apiVersion: v1
kind: Service
metadata:
  name: stats-api
  labels: { app: stats-api }
spec:
  selector: { app: stats-api }
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-api
  labels: { app: stats-api }
spec:
  replicas: 1
  selector:
    matchLabels: { app: stats-api }
  template:
    metadata:
      labels: { app: stats-api }
    spec:
      containers:
        - name: stats-api
          image: tazeemalik/stats-api:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URL
              value: mongodb://textstore:27017/tasksdb
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet: { path: /api/health, port: 3000 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /api/health, port: 3000 }
            initialDelaySeconds: 15
            periodSeconds: 10
